### ISSUE TITLE
Build fails on OS X Mojave

### ISSUE THREAD

**Issue by aknuds1** [pingcap/grpc-rs#344]
I can't build on OS X Mojave v10.14.5 due to a missing header file, Availability.h. I get the following error output when running `cargo build`:

```
./grpc/include/grpc/impl/codegen/port_platform.h:182:10: fatal error: 'Availability.h' file not found
./grpc/include/grpc/impl/codegen/port_platform.h:182:10: fatal error: 'Availability.h' file not found, err: true
thread 'main' panicked at 'Unable to generate grpc bindings: ()', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

What can I do to fix this?

**Comment by nrc** [comment]
You need to install (or update) new XCode libraries (I hit the same problem last week): first check the app store and system settings for any updates and update if necessary, then run `xcode-select --install`

**Comment by aknuds1** [comment]
@nrc Unfortunately, I had already tried both those things and it doesn't help. There are no updates and:

```
$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

**Comment by BusyJay** [comment]
@aknuds1 would you like to verify whether #349 fixes the problem?

**Comment by aknuds1** [comment]
> @aknuds1 would you like to verify whether #349 fixes the problem?

@BusyJay Yes, this works! Thanks!

**Comment by BusyJay** [comment]
It should be fixed.

**Comment by mimoo** [comment]
still getting this error on the last MacOS Catalina
