### ISSUE TITLE
Musl build appears to be broken on master

### ISSUE THREAD

**Issue by dwerner** [pingcap/grpc-rs#233]
I did see an update to grpc-core in the reflog, so maybe that's where it came in, but building with musl fails for me due to a, undefined symbol issue:
```
...
 = note: /usr/bin/ld: <redacted>arget/x86_64-unknown-linux-musl/release/deps/libgrpcio_sys-ba3da7551fead876.rlib(log_linux.cc.o): undefined reference to symbol '__fprintf_chk@@GLIBC_2.3.4'
          //lib/x86_64-linux-gnu/libc.so.6: error adding symbols: DSO missing from command line
          collect2: error: ld returned 1 exit status
```

This works fine in 0.3.1, so I can't help but think that something's changed in grpc-core.

I'm on ubuntu 18.04, utilizing a toolchain built from https://bitbucket.org/GregorR/musl-cross 
`RUST_BACKTRACE=full PATH=/opt/cross/x86_64-linux-musl/bin:$PATH cargo build --release --target=x86_64-unknown-linux-musl`

edit: I should say that this toolchain I'm using still successfully builds my application targeting grpcio 0.3.1 successfully.

**Comment by overvenus** [comment]
Maybe you can build it in an alpine container. It works fine. :thinking: 

```rust
# git rev-parse --short HEAD && pwd && ldd interop_client
0c0b2b2
/root/grpc-rs/target/debug
        /lib/ld-musl-x86_64.so.1 (0x7f96535c6000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f9652785000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f9652573000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f96535c6000)
```

**Comment by dwerner** [comment]
I didn't mention that I'm interested in a static binary - in your example the result is not static. I ended up working around this issue with the "custom linker wrapper" solution proposed here: https://github.com/rust-lang/rust/issues/36710#issuecomment-364623950

**Comment by jocutajar** [comment]
@overvenus 

> Maybe you can build it in an alpine container. It works fine. thinking

Just for the record, that won't help people using procedural macros - me :) as these require dynamic loading on the host.
